[package]
name = "agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "*"
async-trait = "*"
base64 = "*"
bytes = "*"
chrono = { version = "0.4" }
clap = { version = "*", features = ["derive", "env"] }
futures = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tempfile = "*"
thiserror = "*"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "*", features = ["with-serde_json-1", "with-uuid-0_8", "with-chrono-0_4"] }
tokio-util = "*"
tracing = "*"
tracing-subscriber = {version = "*", features = ["json", "env-filter", "fmt", "time"]}
url = "*"
uuid = "*"

[dev-dependencies]
insta = { version = "*", features = ["redactions"] }