[package]
name = "models"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
json = { path = "../json", version = "0.0.0" }
doc = { path = "../doc", version = "0.0.0" }
protocol = { path = "../protocol", version = "0.0.0" }

anyhow = "*"
bytes = "*"
percent-encoding = "*"
prost = "*"
rusqlite = { version = "*", features = ["bundled", "collation", "column_decltype", "functions", "serde_json", "url"] }
schemars = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version =  "*", features = ["raw_value"] }
url = "*"