[package]
name = "estuary"
version = "0.1.0"
authors = ["Johnny Graettinger <johnny531@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
headers = "0.3"
hyper = "0.13"
hyperlocal = "0.7"
itertools = "0.9"
log = "0.4"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version =  "1.0", features = ["raw_value"] }
tempfile = "3.1"
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"