[package]
name = "estuary"
version = "0.1.0"
authors = ["Johnny Graettinger <johnny531@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "derive-worker"
path = "cmd/derive-worker/main.rs"

[[bin]]
name = "estctl"
path = "cmd/estctl/main.rs"

[dependencies]
estuary_json = { path = "json" }
bytes = "^0.5"
chrono = { version = "0.4", features = ["serde"] }
clap = "^2.33" # Used only for CLI binaries.
futures = "^0.3"
headers = "^0.3"
http = "^0.2"
hyper = "^0.13"
hyperlocal = "^0.7"
itertools = "^0.9"
log = "^0.4"
pretty_env_logger = "^0.4"
regex = "^1.3"
rusqlite = { version = "^0.22", features = ["functions", "bundled", "url", "serde_json"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version =  "^1.0", features = ["raw_value"] }
serde_yaml = "^0.8"
thiserror = "^1.0"
tinyvec = {version = "^0.3", features = ["alloc"]}
tokio = { version = "0.2", features = ["full"] }
url = "^2.1"
warp = "0.2"

[dev-dependencies]
tempfile = "^3.1"

