[package]
name = "runtime"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
labels = { path = "../labels", version = "0.0.0" }
protocol = { path = "../protocol", version = "0.0.0" }
models = { path = "../models", version = "0.0.0" }

chrono = { version = "*", features = ["serde"] }
futures = "*"
log = "*"
nix = "*"
prost-types = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version =  "*"}
tempfile = "*"
thiserror = "*"
tokio = { version = "0.2", features = ["full"] }
tonic = { version = "*" }
tracing = "*"
url  = "*"
