[package]
name = "estuary_ffi"
version = "0.1.0"
authors = ["Johnny Graettinger <johnny531@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.53.2"

[dependencies]
thiserror = "1.0.14"

[lib]
path = "lib.rs"