cookie:
    session: ENC[AES256_GCM,data:jK/ydg0=,iv:jjvsEcIvemszRsdsEEpUovkZhyWz7v5pU0SM+HKaGK8=,tag:jYfF1ANqbbLXtZr6H7t+uQ==,type:str]
    keys:
        - ENC[AES256_GCM,data:Oh2NJsaZ0gMq8uST+RP6pC5/5vFrF1cTZGy8TXIJp4Wu7XSWL4dwAxye94c=,iv:HrhcIVY3hBjpsQwPWuWYChsoflwYWhjtAkAMI8+vZpc=,tag:1BZbVGs2WRei+nrdkwsi9g==,type:comment]
        - ENC[AES256_GCM,data:K/U/cmG+eVLU/GFV6FwoeYDOOOUOu+zxXo+9dcreRA346XwDmClL,iv:0DtN8QZo9m2/P6a7M/678WwcZQhzCfeQijsqPgY/Raw=,tag:G0kEIdNT6z4RqDjQW2LLhw==,type:comment]
        #ENC[AES256_GCM,data:3CFvD3ZkIy5mcbWEc/CGtZdmlGtiNZcImmekzLF5Ybs4I+xXSBLASoM2sZo=,iv:mn83lpf/YRsLETDQyo3F/E/VFMmlzvVx76xBBbjQtgY=,tag:1SW6gp6ZGXDuZ8lfm16USw==,type:comment]
        #ENC[AES256_GCM,data:VOkgportSgSJImX5cs/GOo0m3xzenGa4PJ4/mBuere7PljtfSFtH,iv:RROXdov+d6kQx365ctuaVfFqFzJgYdzc53Mic8XXv6o=,tag:B1kp+yXUNXbsZalONaiN3w==,type:comment]
        - encrypt: ENC[AES256_GCM,data:/NPwF6keh6iauNJ7m1WP0lejSfwIe1tKDNjKV/ExOrD39ECVi+WuoQGoFWw=,iv:9a5UaiK72y7KwctUe4XjNIoCwmCX0U4/uGWROKPq53U=,tag:qXvn4JQF6I9ji0386x3nqA==,type:str]
          auth: ENC[AES256_GCM,data:4tLw8A16VypwiM5mV85GnaRuqslh3fTIwnEvfdhOW9CGx15R6qLi75fGCys=,iv:QICxXU1COGDR7OVEZ6+a8uAHOfDTW+s9yj39tClPrMA=,tag:7836FJFph93ZY6o8Le9cEQ==,type:str]
    maxAge: ENC[AES256_GCM,data:yK34,iv:z42O6IWkzVvJiMZKLBboTMJo6vEYamimTI7G0+8MyME=,tag:huRyK3O694a8vjVOItt9Cg==,type:str]
    #ENC[AES256_GCM,data:O7pvCGfqLesJeJnV20nUhkBHgpKZbjnREkkWRhMO1WUO,iv:HVBW9R/eJsoI31rjcfBTc8mFasHhSeiU3q+FFOwQvSU=,tag:RIXPSVCZD6FWcEfnoAeCXg==,type:comment]
    requireSSL: ENC[AES256_GCM,data:+vCunA==,iv:IgYfCpXsKR2plLm1NcOJ/vHn3MVK0j+Z2pvXHffkRbc=,tag:kq5mEuq9OEVU5qUEJgqhqg==,type:bool]
oidc:
    google:
        clientID: ENC[AES256_GCM,data:8cDdv0Aq4sfP8SQlr/S2hJ6JVcBVUBNWbVjO0jpS/gVh4pD39bZXxmanVpICYUUQstuo5ss7GbQ4UjPyHxlV2Pma+Ljzs1OM,iv:QnXa7RuYu6MvTHSBjopePZh/ETp2YMvJe2c/0f2rD3s=,tag:4X6/QtZBZAVEz08vhBBIHA==,type:str]
        clientSecret: ENC[AES256_GCM,data:uIaRSGu+ryd9WD+EV3pihfJa+2FhTkNF4M06YFUk7sjsBOU=,iv:OM+J8jiNH5VGRKtxQAkFkwwcPffvOOMuR87Y0b2qXPo=,tag:ooUCqdkCVKLyTHzZ7CZkHQ==,type:str]
        #ENC[AES256_GCM,data:X7DHnVfAUuDz21go4lzuilpONxDT3tLO7Iz/,iv:x+y6NSCJcYjPMiPoZotTYyEzq0son1LhWXAcJCTNt4Q=,tag:HuW2Kslu83dTQ6cuQOAbLw==,type:comment]
        callbackURL: ENC[AES256_GCM,data:/lPpuyBQJrMKTFwCKdCR7eamrozyEnO5JFp+QRPHcXzZrRZrb+UgdArNoUOy,iv:MUJy1N+8+cOyzzNm2a0BMfeoDUFGrMR0QSfJTolMEbw=,tag:fV+2xv0cfUh8ttAx2dNO2w==,type:str]
        #ENC[AES256_GCM,data:ZVa5xY53FokU1jjctvoG8vcpT+wy,iv:0ikGF/xXoh3nU5pe211uI+FV+R/tS1sWI5tWiCYX47A=,tag:9iA2kY+iz4NK3SAjxp699Q==,type:comment]
        #ENC[AES256_GCM,data:XgXsot5H+5NR8rj+Jat2OR1s31OCibl9iDOmztTspssnkSR89oyRpuWf20sb7b9152bbd7ay8CE=,iv:Hh9RWSCBeEIK7dUTLwOnTbAuJ/ktrpCSELzl+2kLwVg=,tag:wq/lqG/xOclnPxIhUUnmnA==,type:comment]
        scopes:
            - ENC[AES256_GCM,data:fP8GXwg=,iv:rS7Bhwv0QKIhDMh8j3LoNudt29XIITLtHM8H9lesuAE=,tag:uE716sjng1wyci5nT75GvA==,type:str]
            - ENC[AES256_GCM,data:KEZRTgTwZA==,iv:k4WG0TDIml++Ndx0dW38gxoPDsB8oA7lNw+u94abxnQ=,tag:mjIAn0S/wtE+ukP0GxBq0w==,type:str]
tokens:
    maxAge: ENC[AES256_GCM,data:MedC,iv:hp8yTv5Oe2s328vsqp1BmkxFWDK0sucPiqE6jDad1HE=,tag:N9wOOIA/bAeiSZJrkfeHSg==,type:str]
    keys:
        - ENC[AES256_GCM,data:IdodLzNS/iVLMqRNRP50CJvPiYOEhzvcpuXBeX2rbjyahyz1878=,iv:OgLMf7ASZuyBYoNfsWPDU/yPSgmSFKaf/5b82O3dzgU=,tag:PEYVcnDJaij6yU4NIkNVjw==,type:comment]
        - ENC[AES256_GCM,data:0k6gK3RGBQQCsjapa2BKtUYNb1GpiRASZFDlIH2/q95j3jFClMrHKlYN5iJg5fsmILpTiQvm2xIdmrf6u1MnrjTbiuvnSg==,iv:x3Okarh/NOC03lsY+DzDCUm1Zk3E6nLyKjJ3ik7q3+I=,tag:/9hdtxCr/Z+9UcgfokQ6Yw==,type:comment]
        #ENC[AES256_GCM,data:Kl4gUowrPol7QAtnCQsrv4to4f3pqbs/j6SDvTeT4nCjPqbjHa4=,iv:ioXQYaLjlkHGJFCvtnYkOjud9ZyuRBv5Lhy2VNim34o=,tag:ykEpdCAtBp5cSLqhNtyg0Q==,type:comment]
        #ENC[AES256_GCM,data:R/bfrlRyC0gsU3ADICsdq6stsx6dx4DJKDCG6OT3SVUfUvmMveG1n86lix2pVWuy4cT6GH/YVtcWEoRndBPuUp7eTgJeJg==,iv:juk0ReQs2s2Y4gWQAT3Dy9j3/QOU89ynmNAeLy9x1cw=,tag:D98gsXrNAKIOCJb1oUxvAQ==,type:comment]
        - keyID: ENC[AES256_GCM,data:SWSoWw==,iv:IbmeiA+3sGE6C1yUmFhe056eXES3pr3i2DZY7MfxXWY=,tag:/LOapPx8QeVPlWNz6ldOzQ==,type:str]
          ecdsaPrivateKey: ENC[AES256_GCM,data:XEftI6IJY0XMiGfdPIte8ixD40tEghWgXAvmFyDtaqLgnJ5kCs7ehXu43ofFNH3e4inI38ICLQO3qMztOdUen0Z2gGcZiN+KlUxoZj/+iPY4q+J8gLfp6WT62e9zHiNfi1lx+sAK8hSjCnVZ7JnqBeuocKP0NLR6Q49hSud4R2aR5rQA66eCIzuI+QeKbew0ohr7eMOUJiyEN8VxuLPJ9eUQrqoeSsHrAttqoGfxnjcWnFBvRP+7Hdq9Iw3GSGRsENZYdSlhhNdTD4q2ufe3gCjfBbC89GZmRun0l6Zk/AOdF8Q=,iv:703grhwCAhyHkyj/MqA+R6jncztl9vXoSQ67INimP4k=,tag:fI1lSNmQXleaht6+xOE65A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-control/locations/us-central1/keyRings/sops/cryptoKeys/cd-github-control
          created_at: "2022-03-30T16:57:28Z"
          enc: CiQAVMVLq0OIpMCx/KTh14Yg1Vvoy2ou93MhVr5jiMK8cQ9/F1ESSQB9xCUJFUi+DiQwvM1k9IavyVy4nhKQwkiI/5mdjnr9BNBpTf9mRfNhAE2jYdnkG56NOqzDcSy1EkDv4l7K1Iuerc8W38zccPk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-30T16:57:29Z"
    mac: ENC[AES256_GCM,data:uhM1M4W1PiJdDkyPuQCGVqoP90Q9JPsE+LL3ZyZMlalzru0/wqYXDRpCWeff0olyJw4mcfiBXUmFbKvLvRjXcbHfAW92cM9fMTDooS/vYhJNEjYDqpsW8QzOcLx5nbUB/hF58GIiHp1cIyPAJhGYchLTnMWjOKtw6hpRN+8yctM=,iv:BUVp1AF5J7cYIGYpfBE373eTPnMID5KjBz1O8IMEaJU=,tag:Iu3urui9dDb6wdqjiM0ktA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
