[package]
name = "protocol"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
anyhow = "*"
bytes = "*"
humantime-serde = "*"
prost = "*"
prost-types = "*"
serde = "*"
tracing = "*"

[dev-dependencies]
insta = "*"
serde_json = "*"

[build-dependencies]
prost-build = "*"
