[package]
name = "protocol"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
prost = "*"
prost-types = "*"
serde = "*"
tonic = "*"

[dev-dependencies]
insta = "*"
serde_json = "*"

[build-dependencies]
tonic-build = "*"
