[package]
name = "testing"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
derive = { path = "../derive", version = "0.0.0" }
doc = { path = "../doc", version = "0.0.0" }
json = { path = "../json", version = "0.0.0" }
models = { path = "../models", version = "0.0.0" }
protocol = { path = "../protocol", version = "0.0.0" }
runtime = { path = "../runtime", version = "0.0.0" }

futures = "*"
itertools = "*"
pathfinding = "*"
percent-encoding = "*"
prost = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version =  "*"}
superslice = "*"
tracing = "*"
tracing-futures = "*"
thiserror = "*"
tonic = { version = "*" }
url = "*"
